name: BuiltTool Documentation
on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - '**/docs.yml'
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/develop') && github.repository == 'SimCubeLtd/SimCube.BuildTool'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        working-directory: ./docs
        run: |
          npm install
          npm run docs:build
      - name: Deploy
        working-directory: ./docs/.vuepress/dist
        run: |
          git init .
          git config --global user.name "Prom3theu5"
          git config --global user.email "info@simcube.co.uk"
          git fetch https://github.com/SimCubeLtd/simcube-buildtool.github.io.git
          git checkout 220443cd2ab45d486fcee10a65669aff0bda31ab
          git checkout -b master
          git add .
          git commit -am "Deploy Documentation"
          git push --force --set-upstream https://${{secrets.PHATBOYG_PAT}}:x-oauth-basic@github.com/SimCubeLtd/simcube-buildtool.github.io.git master
