name: Main CI-CD

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  SIMCUBE_NUGET_SERVER: https://api.nuget.org/v3/index.json
  SIMCUBE_NUGET_API_KEY: ${{ secrets.PUBLIC_NUGET_TOKEN }}
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build-test-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true

      - name: Build, Test and Pack
        run: |
          dotnet tool restore
          dotnet cake --pack true

      - uses: codecov/codecov-action@v3
        with:
            directory: ./test-output
            files: coverage.cobertura.xml
            fail_ci_if_error: true
            verbose: true

      - name: Push to nuget
        working-directory: artifacts/
        run: dotnet nuget push *.nupkg -s $SIMCUBE_NUGET_SERVER -k $SIMCUBE_NUGET_API_KEY
