name: Pull Requests

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  - pull_request

jobs:
  build-test-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true

      - name: Build, Test and Pack
        run: |
          dotnet tool restore
          dotnet cake

      - uses: codecov/codecov-action@v3
        with:
            directory: ./test-output
            files: coverage.cobertura.xml
            fail_ci_if_error: true
            verbose: true
