name: PUSH

on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build_pack_and_push:
    runs-on: simcube-devserver
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.0.0
      - name: "Clean Artifacts"
        run: rm -f artifacts/*
      - name: "Clean, Restore, Build, Test and Pack"
        env:
          TOOL_VERSION: 1.0.${{ github.run_number }}
        run: |
          dotnet tool restore
          dotnet cake
      - name: Push Template Package to Simcube Nuget
        env:
          nuget_key: ${{ secrets.SIMCUBE_NUGET_TOKEN }}
        run: dotnet nuget push -s http://88.99.64.79:15001/repository/SimcubeRelease/ -k $nuget_key artifacts/*.nupkg
